// Env-configured email delivery. Any provider that accepts
//   POST {EMAIL_API_BASE_URL}/emails  { from, to, subject, text, html }
// with `Authorization: Bearer {EMAIL_API_KEY}` works (Resend, Postmark proxy,
// a mailhog bridge, ...). When unconfigured, sending is skipped rather than failing
// the caller — scheduled reports still generate.
interface EmailConfig {
  baseUrl?: string;
  apiKey?: string;
  from?: string;
}

function cfg(): EmailConfig {
  return {
    baseUrl: process.env.EMAIL_API_BASE_URL?.replace(/\/$/, ""),
    apiKey: process.env.EMAIL_API_KEY,
    from: process.env.EMAIL_FROM || "ImpactLens <reports@impactlens.local>",
  };
}

export function isEmailConfigured(): boolean {
  const c = cfg();
  return Boolean(c.baseUrl && c.apiKey);
}

export interface SendMailResult {
  sent: boolean;
  reason?: string;
}

export async function sendMail(opts: {
  to: string;
  subject: string;
  text: string;
  html?: string;
}): Promise<SendMailResult> {
  const c = cfg();
  if (!c.baseUrl || !c.apiKey) {
    return { sent: false, reason: "email not configured (EMAIL_API_BASE_URL / EMAIL_API_KEY)" };
  }

  const res = await fetch(`${c.baseUrl}/emails`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${c.apiKey}`,
    },
    body: JSON.stringify({
      from: c.from,
      to: [opts.to],
      subject: opts.subject,
      text: opts.text,
      html: opts.html ?? `<pre style="white-space:pre-wrap;font-family:sans-serif">${escapeHtml(opts.text)}</pre>`,
    }),
  });

  if (!res.ok) {
    const body = await res.text().catch(() => "");
    return { sent: false, reason: `${res.status} ${body.slice(0, 200)}` };
  }
  return { sent: true };
}

function escapeHtml(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}

/** Plain-text + html body for a delivered report. */
export function renderReportEmail(report: {
  title: string;
  headline: string | null;
  summary: string;
  narrative: string | null;
  callToAction: string | null;
  type: string;
  tone: string | null;
}): { subject: string; text: string } {
  const text = [
    report.title,
    report.headline ? `\n${report.headline}` : "",
    `\n${report.summary}`,
    report.narrative ? `\n---\n${report.narrative}` : "",
    report.callToAction ? `\n\nNext step: ${report.callToAction}` : "",
    `\n\nType: ${report.type} · Tone: ${report.tone ?? "professional"} · Generated by ImpactLens`,
  ].join("\n");

  return { subject: report.title, text };
}
